spring: 
  profiles:
    active:
    - dev
--- 

server:
  port: 7890


spring:
  profiles: dev
  freemarker:
    suffix: .html
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false

---
server:
  port: 7890


spring:
  profiles: test
  freemarker:
    suffix: .html
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
